### PR TITLE
bug/68: Fixed broken regression test

### LINKED ISSUE #68: Regression test broken
The regression tests broke with the last release.

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #68

### CODE REVIEW

File: src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java [hunk 1]
```diff
@@ -128,10 +128,9 @@ void testManySmallJsonFiles(final TestInfo testInfo) throws Exception {
         final int numberOfJsonFiles = 1_000_000;
         createTestSetupWithSmallJsonFiles(numberOfJsonFiles);
         final String mapping = getMappingDefinitionForSmallJsonFiles();
-        final String bucketAddress = "https://" + SMALL_JSON_FILES_FIXTURE_BUCKET + ".s3."
-                + AWS_S3_TEST_SETUP.getRegion() + ".amazonaws.com/";
-        final ConnectionDefinition connection = SETUP.getExasolObjectFactory().createConnectionDefinition(
-                "SMALL_FILES_BUCKET", bucketAddress, AWS_S3_TEST_SETUP.getUsername(), AWS_S3_TEST_SETUP.getPassword());
+        final JsonObjectBuilder connectionConfig = SETUP.getConnectionConfig();
+        connectionConfig.add("s3Bucket", SMALL_JSON_FILES_FIXTURE_BUCKET);
+        final ConnectionDefinition connection = SETUP.createConnectionDefinition(connectionConfig);
```
Comment (morazow) [inline src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java:133]: :+1:

**Review by morazow — APPROVED** [review]
